services:
  - type: web
    name: nemesis-backend
    env: docker
    region: ohio
    plan: standard
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: POLYGONSCAN_API_KEY
        sync: false
      - key: BSCSCAN_API_KEY
        sync: false
      - key: GEMINI_API_KEYS
        sync: false
      - key: DATABASE_MONGO_URL
        sync: false
      - key: POSTGRES_URI
        sync: false
