name = "nemesis-frontend"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB" # Available in your Pages Functions as env.DB
database_name = "nemesis_intelligence_db"
database_id = "7fcfec1d-362d-445b-af2a-69eac4180aed"

[[kv_namespaces]]
binding = "NEMESIS_CACHE"
id = "f4099ea1458e4e62ba838734f172846f"

[[hyperdrive]]
binding = "database"
id = "2bf62864eaf64708b5a349169d6efc7e"

[vars]
ENVIRONMENT = "production"

# Bind the Pages frontend to the Python backend Worker
[[services]]
binding = "BACKEND"
service = "nemesis-api"
