name = "nemesis-backend"
main = "nemesis_core.py"
compatibility_date = "2024-04-05"
compatibility_flags = ["python_workers"]



[vars]
ENVIRONMENT = "production"
# All other secrets like TATUM_API_KEY, GEMINI_API_KEYS will be securely added via `wrangler secret put`
